# serverless.yml

service: apollo-lambda
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs16.x
  region: ca-central-1
functions:
  graphql:
    handler: src/index.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true